### ISSUE TITLE
demo не работает

### ISSUE THREAD

**Issue by kudesa** [Akurganow/pursuing-nav#11]
подключение jquery и скрипта выглядит так
`
  <script src="//cdn.jsdelivr.net/g/jquery@2,jquery.pursuing-nav,highlight.js@8"></script>`

**Comment by Akurganow** [comment]
@kudesa Только что проверил, все работает, скрипт по ссылке http://cdn.jsdelivr.net/g/jquery@2,jquery.pursuing-nav,highlight.js@8 вполне рабочий.

**Comment by kudesa** [comment]
![pursuings nav opera at 10 32 23](https://cloud.githubusercontent.com/assets/1862552/9987059/1e12542e-604c-11e5-9633-2494c51e80e6.png)

**Comment by Akurganow** [comment]
@kudesa когда переходишь по ссылке http://cdn.jsdelivr.net/g/jquery@2,jquery.pursuing-nav,highlight.js@8, что там?

**Comment by kudesa** [comment]
![404 not found opera at 10 54 21](https://cloud.githubusercontent.com/assets/1862552/9987278/26a75758-604f-11e5-96f5-bc92f5229df8.png)

**Comment by jimaek** [comment]
"Not Found" is not a jsDelivr error. You must have a proxy or something that breaks everything.
Here is an example of jsDelivr errors http://cdn.jsdelivr.net/g/404

**Comment by Akurganow** [comment]
@kudesa @jimaek А вообще jsdelivr работает? Например эта ссылка https://cdn.jsdelivr.net/jquery/3.0.0-alpha1/jquery.js

**Comment by kudesa** [comment]
У меня не работает:
GET https://cdn.jsdelivr.net/ net::ERR_CONNECTION_REFUSED

**Comment by jimaek** [comment]
Disable any proxies you are using. The response is not by jsDelivr, something else answers to you.
Caching proxy, squid, anonymity proxy, other...

**Comment by Akurganow** [comment]
@kudesa Убедись, что у тебя выключены все прокси, страница 404 не такая как у jsdelivr, отвечает тебе не он.

**Comment by kudesa** [comment]
@Akurganow это штатный провайдер, я не знаю кто там блокирует, но через vpn работает

**Comment by Akurganow** [comment]
@kudesa Можешь им в поддержку написать, пожалуйста?

**Comment by kudesa** [comment]
@Akurganow отпишусь, как ответят

**Comment by kudesa** [comment]
@Akurganow извиняюсь за беспокойство, хост был забанен в hosts

**Comment by Akurganow** [comment]
:+1: бывает
